# Numpy

In [ ]:
import numpy as np

## Numpy array

In [ ]:
my_list = [1,2,3]

In [ ]:
type(my_list)

list

In [ ]:
#lista --->  array
np.array(my_list)

array([1, 2, 3])

In [ ]:
type(np.array(my_list))

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[6,7,8]]
my_matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

## Métodos en numpy

In [ ]:
np.array(list(range(0,10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# no te lo lee
np.ones(3,5)

TypeError: data type not understood

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random

## Rand

Devuelve números entre 0 y 1

In [ ]:
np.random.rand(10)

array([0.3843143 , 0.68995893, 0.72187918, 0.16466287, 0.05850883,
       0.28136981, 0.37870849, 0.66261572, 0.92551573, 0.79657555])

In [ ]:
np.random.rand(5,5)

array([[0.50000022, 0.17646474, 0.91982358, 0.60582254, 0.03884101],
       [0.28279209, 0.28847961, 0.4800235 , 0.98994873, 0.01276958],
       [0.03371661, 0.76283107, 0.08646858, 0.38335305, 0.76957922],
       [0.6895756 , 0.94306965, 0.07124345, 0.06290505, 0.21788706],
       [0.35573812, 0.91887782, 0.98088406, 0.06322139, 0.14091499]])

## Rand N
Devuelve números distribución normal

In [ ]:
np.random.randn(5)

array([ 1.23048031,  0.3332617 , -0.3721024 ,  1.21880858, -0.96142859])

In [ ]:
np.random.randn(5,5)

array([[-0.20843919,  0.87607968, -0.55579056,  0.78865914,  1.10674619],
       [ 0.33807925,  2.15931301,  0.37952668, -0.02498455, -1.07960259],
       [ 0.63076832,  0.19082943,  0.7283318 ,  0.4434348 ,  0.06086952],
       [ 1.31009479,  0.04585772, -0.36385371, -0.91226622, -1.07003373],
       [-0.45158188, -0.15290546, -0.69419883, -1.00289302,  0.63483638]])

## Rand int
Devuelve número enteros

In [ ]:
np.random.randint(0,150)

145

In [ ]:
np.random.randint(0,150,50)

array([ 37, 125, 148,  80, 130, 149,  66,  20, 109,  48, 116, 121, 100,
        40,  25,  89,  31,  22, 114,  93, 141,  78,  71,   8,  25,  91,
        49, 108,  45, 112,  95,  25, 126,  78, 123, 125,  75,  77,  10,
        85, 104, 136, 112,  53, 132,  87,  43,  12,  72,  86])

In [ ]:
np.random.randint(0,150,(5,5))

array([[141,  35, 104, 137,  67],
       [ 55,  47,  88,   1, 147],
       [136,  94,  65,  80,  71],
       [ 87,  60,  46,  27, 126],
       [ 24, 131,  13,  93,  32]])

## Atributos

In [ ]:
x = np.random.randint(0,150)
y = np.random.randint(20,741,150)

In [ ]:
x

62

In [ ]:
y

array([568, 513, 206, 542, 118,  76, 691, 653, 153, 660, 300, 473, 586,
       378, 212, 724, 298, 335, 270, 166, 433, 148, 714, 608, 415, 729,
        45, 523, 440, 696, 491, 293, 633, 385, 338,  38, 218, 265,  71,
       230,  95, 481, 194, 232, 154,  93, 590, 672, 240, 659, 735, 548,
       703, 192, 498, 391, 543, 651, 471, 335, 516, 502, 490,  34, 566,
        45,  30,  80, 106, 311, 592, 458, 612,  53, 232, 333, 160, 391,
       227, 670, 347, 236, 341, 275, 642, 114, 106, 293, 715, 125, 373,
       547, 550, 606, 713, 319, 116, 226, 270, 252, 299, 619, 437, 231,
       452, 712, 311, 600, 674, 699, 154, 129, 480, 596, 632, 323,  31,
       638, 183, 664, 138, 484, 492, 132, 231, 602,  88, 172, 304, 182,
       403, 393, 597, 739, 547, 238, 245,  27, 448, 540,  86, 588, 565,
        37, 459, 546, 155,  81, 301, 263])

## Shape

In [ ]:
y.shape

(150,)

In [ ]:
z = np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
z.shape

(5, 5)

In [ ]:
li = np.linspace(0,12)
li

array([ 0.        ,  0.24489796,  0.48979592,  0.73469388,  0.97959184,
        1.2244898 ,  1.46938776,  1.71428571,  1.95918367,  2.20408163,
        2.44897959,  2.69387755,  2.93877551,  3.18367347,  3.42857143,
        3.67346939,  3.91836735,  4.16326531,  4.40816327,  4.65306122,
        4.89795918,  5.14285714,  5.3877551 ,  5.63265306,  5.87755102,
        6.12244898,  6.36734694,  6.6122449 ,  6.85714286,  7.10204082,
        7.34693878,  7.59183673,  7.83673469,  8.08163265,  8.32653061,
        8.57142857,  8.81632653,  9.06122449,  9.30612245,  9.55102041,
        9.79591837, 10.04081633, 10.28571429, 10.53061224, 10.7755102 ,
       11.02040816, 11.26530612, 11.51020408, 11.75510204, 12.        ])

In [ ]:
len(li), li.shape

(50, (50,))

In [ ]:
li.reshape(5,10)

array([[ 0.        ,  0.24489796,  0.48979592,  0.73469388,  0.97959184,
         1.2244898 ,  1.46938776,  1.71428571,  1.95918367,  2.20408163],
       [ 2.44897959,  2.69387755,  2.93877551,  3.18367347,  3.42857143,
         3.67346939,  3.91836735,  4.16326531,  4.40816327,  4.65306122],
       [ 4.89795918,  5.14285714,  5.3877551 ,  5.63265306,  5.87755102,
         6.12244898,  6.36734694,  6.6122449 ,  6.85714286,  7.10204082],
       [ 7.34693878,  7.59183673,  7.83673469,  8.08163265,  8.32653061,
         8.57142857,  8.81632653,  9.06122449,  9.30612245,  9.55102041],
       [ 9.79591837, 10.04081633, 10.28571429, 10.53061224, 10.7755102 ,
        11.02040816, 11.26530612, 11.51020408, 11.75510204, 12.        ]])

In [ ]:
p = np.random.randint(20,741,10)
p

array([258, 605, 481, 654, 691, 422,  94, 216, 206,  89])

In [ ]:
p.max()

691

In [ ]:
p.mean()

371.6

In [ ]:
p.std()

217.30494702146106

In [ ]:
p.argmax()

4

## Operaciones

In [ ]:
p+p

array([ 516, 1210,  962, 1308, 1382,  844,  188,  432,  412,  178])

In [ ]:
p*p

array([ 66564, 366025, 231361, 427716, 477481, 178084,   8836,  46656,
        42436,   7921])

In [ ]:
0/0

ZeroDivisionError: division by zero

In [ ]:
p**3

array([ 17173512, 221445125, 111284641, 279726264, 329939371,  75151448,
          830584,  10077696,   8741816,    704969], dtype=int32)

In [ ]:
np.max(p)

691

In [ ]:
np.sin(p)

array([ 0.37963563,  0.97052075, -0.33001928,  0.52160244, -0.1498176 ,
        0.85553559, -0.24525199,  0.69605849, -0.9746419 ,  0.86006941])

In [ ]:
np.exp(p)

array([1.11680238e+112, 5.59965862e+262, 7.86404148e+208, 1.06804897e+284,
       1.25166179e+300, 1.87185138e+183, 6.66317622e+040, 6.42108015e+093,
       2.91516588e+089, 4.48961282e+038])

In [ ]:
np.sqrt(p)

array([16.0623784 , 24.59674775, 21.9317122 , 25.57342371, 26.28687886,
       20.54263858,  9.69535971, 14.69693846, 14.35270009,  9.43398113])

In [ ]:
p

array([258, 605, 481, 654, 691, 422,  94, 216, 206,  89])

In [ ]:
x = np.where(p==np.max(p))
x

(array([4], dtype=int64),)

In [ ]:
p[x]

array([691])

## Indexación & Slide

In [ ]:
m = np.array(my_matrix)
m

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
m[0][0]

1

In [ ]:
m[0,0]

1

In [ ]:
m[:2][1:]

array([[4, 5, 6]])

In [ ]:
#mejor forma
m[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
n = m.copy()
n

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

## FIN